# Generated by Django 2.0.8 on 2018-09-03 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kategori',
            field=models.ForeignKey(default='0', limit_choices_to={'kode_barang': '-'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='barang.Post'),
        ),
    ]
