# Generated by Django 2.0.8 on 2018-09-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0003_auto_20180903_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='set_kategori',
            field=models.BooleanField(default=False),
        ),
    ]
